### ISSUE TITLE
10.15

### ISSUE THREAD

**Issue by CChuancey** [Vnzen/Hackintosh_hasee_k680e-g6d1_clover#1]
你好，我是和你同机型，不知道你10.15有升级吗。

**Comment by zhboat** [comment]
你好,我也是和你同机型,不知道你用他的efi升级10.15了吗

**Comment by CChuancey** [comment]
我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了



---Original---

**Comment by zhboat** [comment]
> 我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了
> […](#)
> ---Original--- From: "柚木舟"<notifications@github.com&gt; Date: Thu, Oct 10, 2019 09:44 AM To: "Vnzen/Hackintosh_hasee_k680e-g6d1_clover"<Hackintosh_hasee_k680e-g6d1_clover@noreply.github.com&gt;; Cc: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [Vnzen/Hackintosh_hasee_k680e-g6d1_clover] 10.15 (#1) 你好,我也是和你同机型,不知道你用他的efi升级10.15了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了
> […](#)
> ---Original--- From: "柚木舟"<notifications@github.com&gt; Date: Thu, Oct 10, 2019 09:44 AM To: "Vnzen/Hackintosh_hasee_k680e-g6d1_clover"<Hackintosh_hasee_k680e-g6d1_clover@noreply.github.com&gt;; Cc: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [Vnzen/Hackintosh_hasee_k680e-g6d1_clover] 10.15 (#1) 你好,我也是和你同机型,不知道你用他的efi升级10.15了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了
> […](#)
> ---Original--- From: "柚木舟"<notifications@github.com&gt; Date: Thu, Oct 10, 2019 09:44 AM To: "Vnzen/Hackintosh_hasee_k680e-g6d1_clover"<Hackintosh_hasee_k680e-g6d1_clover@noreply.github.com&gt;; Cc: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [Vnzen/Hackintosh_hasee_k680e-g6d1_clover] 10.15 (#1) 你好,我也是和你同机型,不知道你用他的efi升级10.15了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了
> […](#)
> ---Original--- From: "柚木舟"<notifications@github.com&gt; Date: Thu, Oct 10, 2019 09:44 AM To: "Vnzen/Hackintosh_hasee_k680e-g6d1_clover"<Hackintosh_hasee_k680e-g6d1_clover@noreply.github.com&gt;; Cc: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [Vnzen/Hackintosh_hasee_k680e-g6d1_clover] 10.15 (#1) 你好,我也是和你同机型,不知道你用他的efi升级10.15了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

emmm,我没有远景论坛的账号..方便的话可以麻烦您分享一下链接吗,我也想升级10.15 
自己折腾的10.14.3很多小毛病,所以想试试别人的efi

**Comment by zhboat** [comment]
> 我用自己的efi升级了10.15，efi放在了远景(95.5%完成度10.14版本那个)。升级完会进不去系统，需要更新clover、lilu和whatevergreen驱动到最新版本。现在已经完美了
> […](#)
> ---Original--- From: "柚木舟"<notifications@github.com&gt; Date: Thu, Oct 10, 2019 09:44 AM To: "Vnzen/Hackintosh_hasee_k680e-g6d1_clover"<Hackintosh_hasee_k680e-g6d1_clover@noreply.github.com&gt;; Cc: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [Vnzen/Hackintosh_hasee_k680e-g6d1_clover] 10.15 (#1) 你好,我也是和你同机型,不知道你用他的efi升级10.15了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


emmm,我没有远景论坛的账号,可以麻烦您分享一下链接吗,我也想升级10.15
(自己折腾的10.14.3很多小毛病所以想试试别人的efi)

**Comment by CChuancey** [comment]
自己去下，懒得发

**Comment by anwenzen** [comment]
我在最近换电脑了。。。。。
